import { previewSlugs } from "virtual:preview-slugs"
import { buildDoc, sortDocs } from "./content-parser"
import type { ServiceDoc, ServiceTokens } from "./content-types"

const RAW_MODULES: Record<string, string> = import.meta.glob("/services/*.md", {
  query: "?raw",
  import: "default",
  eager: true,
})

// Machine-readable token sidecars (`services/{slug}.tokens.json`), generated by
// `pnpm tokens:build` and human-reviewed. Vite parses JSON to objects, so the
// runtime cost is a Map lookup — no YAML/markdown parsing at request time. An
// entry without a sidecar simply leaves `doc.tokens` undefined, and the detail
// page renders no token-card section for it (graceful during rollout).
const TOKEN_MODULES: Record<string, unknown> = import.meta.glob(
  "/services/*.tokens.json",
  { import: "default", eager: true },
)

function coerceServiceTokens(data: unknown, filePath: string): ServiceTokens {
  if (typeof data !== "object" || data === null) {
    throw new Error(
      `[content-collection] token sidecar ${filePath} must be a JSON object`,
    )
  }
  const d = data as Record<string, unknown>
  for (const key of ["colors", "typography", "spacing", "radius"] as const) {
    if (d[key] !== undefined && !Array.isArray(d[key])) {
      throw new Error(
        `[content-collection] ${filePath}: tokens.${key} must be an array`,
      )
    }
  }
  // Field-level guard for colors only. `value` is rendered straight into a CSS
  // `background`, so a malformed entry would silently paint an empty swatch (or
  // inject an arbitrary CSS value) — a silent visual failure worth a loud throw.
  // Typography / spacing / radius fields are deliberately NOT guarded here: they
  // are all optional and land in `style={{ fontSize, lineHeight, … }}`, where an
  // invalid value is simply ignored by CSS (graceful degradation, not a silent
  // gap), so the asymmetry is intentional.
  for (const color of (d.colors as Array<unknown> | undefined) ?? []) {
    if (
      typeof color !== "object" ||
      color === null ||
      typeof (color as { name?: unknown }).name !== "string" ||
      typeof (color as { value?: unknown }).value !== "string"
    ) {
      throw new Error(
        `[content-collection] ${filePath}: every color needs a string name and value`,
      )
    }
  }
  return {
    colors: (d.colors as ServiceTokens["colors"] | undefined) ?? [],
    typography: (d.typography as ServiceTokens["typography"] | undefined) ?? [],
    spacing: (d.spacing as ServiceTokens["spacing"] | undefined) ?? [],
    radius: (d.radius as ServiceTokens["radius"] | undefined) ?? [],
  }
}

const TOKENS_BY_SLUG = new Map<string, ServiceTokens>(
  Object.entries(TOKEN_MODULES).map(([filePath, data]) => [
    filePath.replace(/^.*\/(.+)\.tokens\.json$/, "$1"),
    coerceServiceTokens(data, filePath),
  ]),
)

const DOCS: Array<ServiceDoc> = sortDocs(
  Object.entries(RAW_MODULES).map(([filePath, raw]) => {
    const doc = buildDoc(filePath, raw)
    const tokens = TOKENS_BY_SLUG.get(doc.frontmatter.slug)
    return tokens ? { ...doc, tokens } : doc
  }),
)

const BY_SLUG = new Map(DOCS.map((d) => [d.frontmatter.slug, d]))

// A service has a preview when public preview assets include
// {slug}/light.html. The Vite plugin exposes only the slug list, avoiding
// JavaScript imports from the public directory.
const SLUGS_WITH_PREVIEW = new Set(previewSlugs)

export function getAllServices(): Array<ServiceDoc> {
  return DOCS
}

export function getServiceBySlug(slug: string): ServiceDoc | undefined {
  return BY_SLUG.get(slug)
}

export function hasPreview(slug: string): boolean {
  return SLUGS_WITH_PREVIEW.has(slug)
}

// Re-export so existing imports (tests, route head() callbacks) keep working
// without caring whether the helper lives in content-collection or content-parser.
export { truncateForMeta } from "./content-parser"
